=== FCS_CKM.1 Cryptographic Key Generation

*_Note: If certifying with the US Scheme (NIAP), ACVP testing fulfills the test requirements._*

The following tests require the developer to provide access to a test platform that provides the evaluator with tools that are typically not found on factory products. Generation of long-term cryptographic keys (i.e. keys that are not ephemeral keys/session keys) might be performed automatically (e.g. during initial start-up). Testing of key generation must cover not only administrator invoked key generation but also automated key generation (if supported).

*Key Generation for FIPS PUB 186-4 RSA Schemes*

The evaluator shall verify the implementation of RSA Key Generation by the TOE using the Key Generation test. This test verifies the ability of the TSF to correctly produce values for the key components including the public verification exponent _e_, the private prime factors _p_ and _q_, the public modulus _n_ and the calculation of the private signature exponent _d_.
Key Pair generation specifies 5 ways (or methods) to generate the primes _p_ and _q_. These include:

. Random Primes:

* Provable primes
* Probable primes

. Primes with Conditions:

* Primes p1, p2, q1, q2, p and q shall all be provable primes
* Primes p1, p2, q1, and q2 shall be provable primes and p and q shall be probable primes
* Primes p1, p2, q1, q2, p and q shall all be probable primes

To test the key generation method for the Random Provable primes method and for all the Primes with Conditions methods, the evaluator must seed the TSF key generation routine with sufficient data to deterministically generate the RSA key pair. This includes the random seed(s), the public exponent of the RSA key, and the desired key length. For each key length supported, the evaluator shall have the TSF generate 25 key pairs. The evaluator shall verify the correctness of the TSF’s implementation by comparing values generated by the TSF with those generated from a known good implementation.

*Key Generation for Elliptic Curve Cryptography (ECC)*

_FIPS 186-4 ECC Key Generation Test_

For each supported NIST curve, i.e., P-256, P-384 and P-521, the evaluator shall require the implementation under test (IUT) to generate 10 private/public key pairs. The private key shall be generated using an approved random bit generator (RBG). To determine correctness, the evaluator shall submit the generated key pairs to the public key verification (PKV) function of a known good implementation.

_FIPS 186-4 Public Key Verification (PKV) Test_

For each supported NIST curve, i.e., P-256, P-384 and P-521, the evaluator shall generate 10 private/public key pairs using the key generation function of a known good implementation and modify five of the public key values so that they are incorrect, leaving five values unchanged (i.e., correct). The evaluator shall obtain in response a set of 10 PASS/FAIL values.

*Key Generation for FIPS PUB 186-5*

_FIPS 186-5 Key Generation Test_

For the Ed25519 curve, the evaluator shall require the implementation under test (IUT) to generate 10 private/public key pairs. The private key shall be generated using an approved random bit generator (RBG). To determine correctness, the evaluator shall submit the generated key pairs to the public key verification (PKV) function of a known good implementation.

_FIPS 186-5 Key Verification Test_

For the Ed25519 curve, the evaluator shall generate 10 private/public key pairs using the key generation function of a known good implementation and modify five of the public key values so that they are incorrect, leaving five values unchanged (i.e., correct). The evaluator shall obtain in response a set of 10 PASS/FAIL values.

*Key Generation for Finite-Field Cryptography (FFC)*

The evaluator shall verify the implementation of the Parameters Generation and the Key Generation for FFC by the TOE using the Parameter Generation and Key Generation test. This test verifies the ability of the TSF to correctly produce values for the field prime p, the cryptographic prime q (dividing p-1), the cryptographic group generator g, and the calculation of the private key x and public key y.
The Parameter generation specifies 2 ways (or methods) to generate the cryptographic prime q and the field prime p:

* Primes q and p shall both be provable primes 
* Primes q and field prime p shall both be probable primes

and two ways to generate the cryptographic group generator g:

* Generator g constructed through a verifiable process
* Generator g constructed through an unverifiable process.

The Key generation specifies 2 ways to generate the private key x:

* len(q) bit output of RBG where 1 <=x <= q-1 
* len(q) + 64 bit output of RBG, followed by a mod q-1 operation and a +1 operation, where 1<= x<=q-1.

The security strength of the RBG must be at least that of the security offered by the FFC parameter set.
To test the cryptographic and field prime generation method for the provable primes method and/or the group generator g for a verifiable process, the evaluator must seed the TSF parameter generation routine with sufficient data to deterministically generate the parameter set.
For each key length supported, the evaluator shall have the TSF generate 25 parameter sets and key pairs. The evaluator shall verify the correctness of the TSF’s implementation by comparing values generated by the TSF with those generated from a known good implementation. Verification must also confirm

* g != 0,1
* q divides p-1
* g^q mod p = 1
* g^x mod p = y

for each FFC parameter set and key pair.

*FFC Schemes using “safe-prime” groups*

Testing for FFC Schemes using safe-prime groups is done as part of testing in CKM.2.1. +

